[package]
name = "fdo-data"
version = "0.1.0"
edition = "2018"

[features]
capi = []

[lib]
crate-type = ["cdylib"]

[dependencies]
fdo-data-formats = { path = "../data-formats", version = "0.1.0" }
libc = "0.2"

[dev-dependencies]
tempfile = "3.2.0"
assert-str = "0.1"
