[workspace]
members = [
    "data-formats",
    "http-wrapper",
    "store",

    "client-linuxapp",
    "owner-onboarding-service",
    "owner-tool",
    "rendezvous-server",
    "manufacturing-server",
    "manufacturing-client",

    "integration-tests",
]
