---
session_store_driver: Directory
session_store_config: /path/to/sessions/
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /path/to/ownership_vouchers/
trusted_device_keys_path: /path/to/keys/device_ca_cert.pem
owner_private_key_path: /path/to/keys/owner_key.der
owner_public_key_path: /path/to/keys/owner_cert.pem
bind: 0.0.0.0:8081
service_info:
  rhsm_organization_id: 6454382
  rhsm_activation_key: SDOkey
  rhsm_run_insights: true
  sshkey_user: admin
  sshkey_key: "testkey"
