---
session_store_driver: Directory
session_store_config: /path/to/sessions/
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /path/to/ownership_vouchers/
trusted_device_keys_path: /path/to/keys/device_ca_cert.pem
owner_private_key_path: /path/to/keys/owner_key.der
owner_public_key_path: /path/to/keys/owner_cert.pem
owner_addresses:
- transport: HTTP
  port: 8081
  addresses:
    - dns_name: fdo.example.com
report_to_rendezvous_endpoint_enabled: false
bind: 0.0.0.0:8081
service_info:
  sshkey_user: admin
  sshkey_key: "testkey"
  files:
  - path: /device/etc/hosts
    permissions: 644
    source_path: /local/etc/hosts
  - path: /device/etc/resolv.conf
    source_path: /local/etc/resolv.conf
  commands:
  - command: ls
    args:
    - /etc/hosts
    return_stdout: true
    return_stderr: true
  - command: ls
    args:
    - /etc/doesnotexist/test
    may_fail: true
    return_stdout: true
    return_stderr: true
  - command: touch
    args:
    - /tmp/command-testfile